Repository WildCodeSchool/orleans-0218-regioncentre, pull requests merged in 2018-07, with the labels that each got.

#179 Fix security
  app/config/security.yml
Labels: Reviewed by PO

#189 S8 us04 delete last comment
  app/Resources/views/comment/delete.html.twig
  app/Resources/views/sheet/show.html.twig
  src/AppBundle/Controller/CommentController.php
  src/AppBundle/Controller/SheetController.php
Labels: Reviewed by PO

#193 Dev to Master S8_03-07
  app/Resources/views/admin/management.html.twig
  app/Resources/views/admin/management/analyse.html.twig
  app/Resources/views/admin/management/job.html.twig
  app/Resources/views/admin/management/management_template.html.twig
  app/Resources/views/admin/management/school.html.twig
  app/Resources/views/admin/management/status.html.twig
  app/Resources/views/admin/management/user.html.twig
  app/Resources/views/analysis/new.html.twig
  app/Resources/views/comment/delete.html.twig
  app/Resources/views/layout_admin.html.twig
  app/Resources/views/lycee/new.html.twig
  app/Resources/views/metier/new.html.twig
  app/Resources/views/sheet/show.html.twig
  app/Resources/views/statut/new.html.twig
  app/Resources/views/user/new.html.twig
  app/config/security.yml
  src/AppBundle/Controller/CommentController.php
  src/AppBundle/Controller/HistorySheetController.php
  src/AppBundle/Controller/ManagementController.php
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/Form/HistorySheetType.php
Labels: Reviewed by PO

#180 Fix department in user
  app/Resources/views/user/new.html.twig
  assets/scss/main.scss
  src/AppBundle/Entity/Department.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/HistorySheetType.php
  src/AppBundle/Form/UserType.php
Labels: Correction Done

#194 Envoi d'un courriel lors du changement de statut
  app/Resources/views/email/status_change.html.twig
  src/AppBundle/Controller/SheetController.php
Labels: Reviewed by PO

#198 Dev to Master
  app/Resources/views/email/status_change.html.twig
  app/Resources/views/user/new.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/Entity/Department.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/HistorySheetType.php
  src/AppBundle/Form/UserType.php
Labels: Reviewed by PO

#200 Fix s8 pagegestion
  src/AppBundle/Controller/ManagementController.php
Labels: Reviewed by PO

#201 Fix s8 route errors
  app/config/routing.yml
  app/config/routing_dev.yml
Labels: Reviewed by PO

#207 S8_us02_forgotten_password
  app/Resources/FOSUserBundle/views/Resetting/check_email.html.twig
  app/Resources/FOSUserBundle/views/Resetting/request.html.twig
  app/Resources/FOSUserBundle/views/Resetting/reset.html.twig
  app/Resources/FOSUserBundle/views/Security/login.html.twig
  assets/scss/main.scss
  assets/scss/variables.scss
Labels: Reviewed by PO

#199 S8 us05 sheet create alternative contact
  app/Resources/views/sheet/new.html.twig
  app/Resources/views/sheet/show.html.twig
  src/AppBundle/Entity/Sheet.php
  src/AppBundle/Form/SheetType.php
Labels: Correction Done

#190 Fix admin button
  app/Resources/views/lycee/edit.html.twig
  app/Resources/views/metier/edit.html.twig
  app/Resources/views/user/new.html.twig
  assets/scss/form.scss
  assets/scss/main.scss
  assets/scss/variables.scss
  src/AppBundle/Controller/MetierController.php
Labels: Correction Done

#206 Fix s8 ajout edit mail contact
  app/Resources/FOSUserBundle/views/Profile/edit.html.twig
  app/Resources/FOSUserBundle/views/Profile/show.html.twig
  src/AppBundle/Form/ProfilType.php
Labels: Reviewed by PO

#203 Fix s8 history school
  app/Resources/views/school/history.html.twig
  src/AppBundle/Controller/HistorySheetController.php
Labels: Reviewed by PO

#208 S8_US01_nom_et_sit_et_date_sur_commentaire
  app/Resources/views/sheet/show.html.twig
  assets/scss/main.scss
Labels: Correction Done

#215 FIX_sheet_nom_du_lycée
  app/Resources/views/sheet/show.html.twig
Labels: Reviewed by PO

#205 Fix find by
  app/Resources/views/admin/home.html.twig
  app/Resources/views/layout_admin.html.twig
  src/AppBundle/Controller/HistorySheetController.php
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/Service/AfterLoginRedirection.php
Labels: Change Requested

#225 Fix_Ajout d'un toggle dans sheet new
  app/Resources/views/sheet/new.html.twig
  assets/js/app.js
  assets/scss/main.scss
  assets/scss/toggle.scss
  src/AppBundle/Entity/Sheet.php
  src/AppBundle/Form/SheetType.php
Labels: Reviewed by PO

#230 fix color in table
  assets/scss/main.scss
  assets/scss/variables.scss
Labels: Reviewed by PO

#233 Fix_supprimer les index et show du lycee et fix routs liste du lycee
  app/Resources/views/lycee/edit.html.twig
  app/Resources/views/lycee/index.html.twig
  app/Resources/views/lycee/show.html.twig
  src/AppBundle/Controller/LyceeController.php
Labels: Reviewed by PO

#236 [UX] Lien pour changer le password #217
  app/Resources/FOSUserBundle/views/ChangePassword/change_password.html.twig
  app/Resources/FOSUserBundle/views/Profile/edit.html.twig
Labels: Reviewed by PO

#239 Fix lycee acceuil
  app/Resources/views/school/index.html.twig
  src/AppBundle/Controller/SheetController.php
Labels: Reviewed by PO

#240 fix_responsive_commentaire
  app/Resources/views/sheet/show.html.twig
Labels: Reviewed by PO

#241 [Security] delete d'un commentaire qui n'est pas le dernier #214
  assets/scss/main.scss
  src/AppBundle/Controller/CommentController.php
Labels: Reviewed by PO

#238 Fix_ajouter ligne nouvelle fiche a navbar
  app/Resources/views/layout_admin.html.twig
  app/Resources/views/school/index.html.twig
Labels: Correction Done

#243 fix path et rediretion des new/edit et des bouton
  app/Resources/views/emop/sheet_edit.html.twig
  app/Resources/views/layout_admin.html.twig
  app/Resources/views/sheet/show.html.twig
  src/AppBundle/Controller/StatutController.php
Labels: Reviewed by PO

#245 correction des vue d'édition et de créatin d'analyse, plus édition fiche
  app/Resources/views/analysis/edit.html.twig
  app/Resources/views/analysis/new.html.twig
  app/Resources/views/emop/sheet_edit.html.twig
  assets/scss/form.scss
  src/AppBundle/Controller/AnalysisController.php
  src/AppBundle/Controller/LyceeController.php
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/Controller/StatutController.php
  src/AppBundle/Controller/UserController.php
Labels: Reviewed by PO

#242 [UX] Page gestion admin #222 #234
  app/Resources/views/admin/management/school.html.twig
  src/AppBundle/Controller/ManagementController.php
  src/AppBundle/Form/HistorySheetType.php
  src/AppBundle/Repository/LyceeRepository.php
Labels: Reviewed by PO

#244 S7_US05_new_comment_mail
  app/Resources/views/email/comment_mail.html.twig
  app/Resources/views/email/forgotten_password.html.twig
  src/AppBundle/Controller/SheetController.php
Labels: Reviewed by PO

#246 reglage responsive, titre acceuil admin et bouton analysis new
  app/Resources/views/admin/home.html.twig
  app/Resources/views/admin/management/management_template.html.twig
  app/Resources/views/sheet/new.html.twig
  app/Resources/views/user/new.html.twig
Labels: Reviewed by PO

#247 Fix_SCSS_roles_color
  assets/scss/variables.scss
Labels: Reviewed by PO

#248 S7_US05_New_comment_mail
  src/AppBundle/Controller/SheetController.php
Labels: Reviewed by PO

#249 [UX] Ajouter les portraits dans les commentaires #232
  app/Resources/FOSUserBundle/views/Profile/show.html.twig
  app/Resources/views/sheet/show.html.twig
  assets/scss/main.scss
  web/images/avatar/avatar_ADMIN.png
  web/images/avatar/avatar_EMOP.png
  web/images/avatar/avatar_SITE.png
Labels: Reviewed by PO

#250 Add pagination sur user gestion / correctif filtre
  app/Resources/views/admin/management/management_template.html.twig
  app/Resources/views/admin/management/user.html.twig
  app/Resources/views/user/new.html.twig
  assets/scss/main.scss
  assets/scss/variables.scss
  src/AppBundle/Controller/ManagementController.php
  src/AppBundle/Repository/UserRepository.php
Labels: Correction Done

#252 Fix mise en forme fiche
  app/Resources/views/sheet/show.html.twig
Labels: Reviewed by PO

#253 FIX home admin + responsive gestion
  app/Resources/views/admin/home.html.twig
  app/Resources/views/admin/management/management_template.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#254 Lors de la rédaction d'un commentaire, si un saut de ligne est rentré…
  app/Resources/views/sheet/show.html.twig
Labels: Reviewed by PO

#255 FIX_Creation title + ajout du favicon
  app/Resources/FOSUserBundle/views/Profile/edit.html.twig
  app/Resources/FOSUserBundle/views/Profile/show.html.twig
  app/Resources/FOSUserBundle/views/Security/login.html.twig
  app/Resources/views/admin/history.html.twig
  app/Resources/views/admin/home.html.twig
  app/Resources/views/admin/management/management_template.html.twig
  app/Resources/views/analysis/edit.html.twig
  app/Resources/views/analysis/index.html.twig
  app/Resources/views/analysis/new.html.twig
  app/Resources/views/analysis/show.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/emop/history_emop.html.twig
  app/Resources/views/emop/home.html.twig
  app/Resources/views/emop/sheet_edit.html.twig
  app/Resources/views/lycee/edit.html.twig
  app/Resources/views/lycee/new.html.twig
  app/Resources/views/metier/edit.html.twig
  app/Resources/views/metier/index.html.twig
  app/Resources/views/metier/new.html.twig
  app/Resources/views/metier/show.html.twig
  app/Resources/views/school/history.html.twig
  app/Resources/views/school/index.html.twig
  app/Resources/views/sheet/edit.html.twig
  app/Resources/views/sheet/index.html.twig
  app/Resources/views/sheet/new.html.twig
  app/Resources/views/sheet/show.html.twig
  app/Resources/views/statut/edit.html.twig
  app/Resources/views/statut/index.html.twig
  app/Resources/views/statut/new.html.twig
  app/Resources/views/statut/show.html.twig
  app/Resources/views/user/edit.html.twig
  app/Resources/views/user/index.html.twig
  app/Resources/views/user/new.html.twig
  app/Resources/views/user/show.html.twig
  web/favicon.ico
  web/images/favicon.ico
Labels: Reviewed by PO

#257 FIX_mail_comment
  src/AppBundle/Controller/SheetController.php
Labels: Reviewed by PO

#256 Fix_Création d'un user
  app/Resources/views/user/new.html.twig
  assets/js/app.js
  assets/scss/main.scss
  src/AppBundle/Form/UserType.php
Labels: Correction Done

#258 Fix redirect defaut
  src/AppBundle/Controller/DefaultController.php
Labels: Reviewed by PO

#259 Fix Responsive Toggle
  app/Resources/views/sheet/new.html.twig
  assets/scss/main.scss
  assets/scss/toggle.scss
Labels: Reviewed by PO

#260 FIX redirection apres add user
  app/Resources/views/analysis/new.html.twig
  app/Resources/views/metier/new.html.twig
  src/AppBundle/Controller/UserController.php
Labels: Reviewed by PO

#262 Fix_sheet_show_responsive
  app/Resources/views/sheet/show.html.twig
  assets/scss/main.scss
  src/AppBundle/Form/CommentType.php
Labels: Reviewed by PO

#263 fix redirect create analysis
  src/AppBundle/Controller/AnalysisController.php
Labels: Reviewed by PO

#268 Fix gestion
  app/Resources/views/admin/management/management_template.html.twig
Labels: Reviewed by PO

#266 Fix_sheet_edit
  app/Resources/views/emop/sheet_edit.html.twig
  src/AppBundle/Controller/SheetController.php
Labels: Reviewed by PO

#264 READ.me & Guide d'utilisation
  README.md
Labels: Correction Done

#270 fix validation user emop/lycee
  app/Resources/views/admin/history.html.twig
  app/Resources/views/user/new.html.twig
  assets/js/app.js
  assets/scss/main.scss
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/UserType.php
Labels: Reviewed by PO

#271 correction des fixture + limit
  app/Resources/views/sheet/show.html.twig
  src/AppBundle/Controller/HistorySheetController.php
  src/AppBundle/DataFixtures/SheetFixtures.php
Labels: Reviewed by PO

#272 Fix_sheet_edit
  app/Resources/views/emop/sheet_edit.html.twig
Labels: Reviewed by PO

#273 fix security, route register
  app/Resources/FOSUserBundle/views/Registration/register.html.twig
  app/config/routing.yml
  app/config/routing_dev.yml
Labels: Reviewed by PO

#274 dev to master
  README.md
  app/Resources/FOSUserBundle/views/Registration/register.html.twig
  app/Resources/views/admin/history.html.twig
  app/Resources/views/emop/sheet_edit.html.twig
  app/Resources/views/sheet/show.html.twig
  app/Resources/views/user/new.html.twig
  app/config/routing.yml
  app/config/routing_dev.yml
  assets/js/app.js
  assets/scss/main.scss
  src/AppBundle/Controller/HistorySheetController.php
  src/AppBundle/DataFixtures/SheetFixtures.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/UserType.php
Labels: Reviewed by PO

#276 fix_management_analyzes_table
  app/Resources/views/admin/management/analyse.html.twig
  app/Resources/views/admin/management/management_template.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#277 Fix date
  app/Resources/views/admin/history.html.twig
  app/Resources/views/admin/home.html.twig
  app/Resources/views/emop/history_emop.html.twig
  app/Resources/views/emop/home.html.twig
  app/Resources/views/emop/sheet_edit.html.twig
  app/Resources/views/school/history.html.twig
  app/Resources/views/sheet/show.html.twig
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/Entity/Sheet.php
  src/AppBundle/Form/SheetType.php
Labels: Correction Done, Reviewed by PO

#279 Fix pills orthograf
  app/Resources/views/admin/history.html.twig
  app/Resources/views/admin/home.html.twig
  app/Resources/views/emop/history_emop.html.twig
  app/Resources/views/emop/home.html.twig
  app/Resources/views/school/history.html.twig
Labels: Reviewed by PO

#281 Fix user connec
  assets/js/app.js
  src/AppBundle/Entity/User.php
Labels: Reviewed by PO

#283 Fix orthographe
  src/AppBundle/Form/SheetType.php
Labels: Reviewed by PO

#284 autres corrections orthographiques
  app/Resources/views/sheet/show.html.twig
Labels: Reviewed by PO

#287 not required date, titre show, msg alert
  src/AppBundle/Entity/Sheet.php
  src/AppBundle/Form/SheetType.php
Labels: Reviewed by PO

#292 Fix_user_table_more_info
  app/Resources/views/admin/management/user.html.twig
  src/AppBundle/DataFixtures/UserFixtures.php
Labels: Reviewed by PO

#293 fix date picker /ok
  src/AppBundle/Entity/Sheet.php
  src/AppBundle/Form/SheetType.php
Labels: Reviewed by PO

#299 quickfix
  src/AppBundle/Form/SheetType.php
Labels: Reviewed by PO

#294 remplacement du terme 'lycée' par le terme 'site'
  app/Resources/views/admin/history.html.twig
  app/Resources/views/admin/home.html.twig
  app/Resources/views/admin/management/management_template.html.twig
  app/Resources/views/emop/history_emop.html.twig
  app/Resources/views/emop/home.html.twig
  app/Resources/views/lycee/edit.html.twig
  app/Resources/views/lycee/new.html.twig
  app/Resources/views/school/history.html.twig
  src/AppBundle/Controller/LyceeController.php
  src/AppBundle/Entity/Lycee.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/LyceeType.php
  src/AppBundle/Form/UserType.php
Labels: Correction Done, Reviewed by PO

#298 emails_template_sheet_id
  app/Resources/views/email/forgotten_password.html.twig
  app/Resources/views/email/sheet_create.html.twig
  app/Resources/views/email/status_change.html.twig
  src/AppBundle/Controller/SheetController.php
Labels: Correction Done, Reviewed by PO

#297 Fix add link
  app/Resources/views/sheet/new.html.twig
  app/Resources/views/sheet/show.html.twig
  src/AppBundle/Entity/Sheet.php
  src/AppBundle/Form/SheetType.php
Labels: Correction Done

#301 fix commentaire
  app/Resources/views/school/index.html.twig
  app/Resources/views/sheet/show.html.twig
Labels: Reviewed by PO

#300 Remove username field
  app/Resources/views/email/comment_mail.html.twig
  app/Resources/views/email/forgotten_password.html.twig
  app/Resources/views/email/password_resetting.html.twig
  app/Resources/views/layout_admin.html.twig
  app/Resources/views/user/new.html.twig
  src/AppBundle/Controller/UserController.php
Labels: Correction Done

#302 retouche
  README.md
Labels: Reviewed by PO

#304 fix_dev
  app/Resources/views/email/comment_mail.html.twig
  app/Resources/views/email/password_resetting.html.twig
  app/Resources/views/layout_admin.html.twig
  app/Resources/views/sheet/show.html.twig
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/Entity/Sheet.php
Labels: Reviewed by PO

#305 dev to master
  README.md
  app/Resources/views/admin/history.html.twig
  app/Resources/views/admin/home.html.twig
  app/Resources/views/admin/management/management_template.html.twig
  app/Resources/views/admin/management/user.html.twig
  app/Resources/views/email/comment_mail.html.twig
  app/Resources/views/email/forgotten_password.html.twig
  app/Resources/views/email/password_resetting.html.twig
  app/Resources/views/email/sheet_create.html.twig
  app/Resources/views/email/status_change.html.twig
  app/Resources/views/emop/history_emop.html.twig
  app/Resources/views/emop/home.html.twig
  app/Resources/views/layout_admin.html.twig
  app/Resources/views/lycee/edit.html.twig
  app/Resources/views/lycee/new.html.twig
  app/Resources/views/school/history.html.twig
  app/Resources/views/school/index.html.twig
  app/Resources/views/sheet/new.html.twig
  app/Resources/views/sheet/show.html.twig
  app/Resources/views/user/new.html.twig
  src/AppBundle/Controller/LyceeController.php
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/Controller/UserController.php
  src/AppBundle/DataFixtures/UserFixtures.php
  src/AppBundle/Entity/Lycee.php
  src/AppBundle/Entity/Sheet.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/CommentType.php
  src/AppBundle/Form/LyceeType.php
  src/AppBundle/Form/SheetType.php
  src/AppBundle/Form/UserType.php
Labels: Reviewed by PO

#306 Fix date souhaitee fin
  app/Resources/views/school/history.html.twig
  src/AppBundle/Entity/Sheet.php
Labels: Reviewed by PO

#307 Dev to master
  app/Resources/views/school/history.html.twig
  src/AppBundle/Entity/Sheet.php
Labels: Reviewed by PO
