Repository WildCodeSchool/orleans-0218-regioncentre, pull requests merged in 2018-06, with the labels that each got.

#39 S3_US03-Entity-Statut
  app/AppKernel.php
  app/Resources/views/statut/edit.html.twig
  app/Resources/views/statut/index.html.twig
  app/Resources/views/statut/new.html.twig
  app/Resources/views/statut/show.html.twig
  assets/scss/form.scss
  src/AppBundle/Controller/StatutController.php
  src/AppBundle/Entity/Statut.php
  src/AppBundle/Form/StatutType.php
  src/AppBundle/Repository/StatutRepository.php
  src/AppBundle/Tests/Controller/StatutControllerTest.php
Labels: Correction Done, Reviewed by PO

#40 fix fixture
  app/AppKernel.php
Labels: Reviewed by PO

#38 S3_US08 fosuser - create user
  app/Resources/views/base.html.twig
  app/Resources/views/user/index.html.twig
  app/Resources/views/user/new.html.twig
  app/Resources/views/user/show.html.twig
  app/config/security.yml
  src/AppBundle/AppBundle.php
  src/AppBundle/Controller/UserController.php
  src/AppBundle/DataFixtures/UserFixtures.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/RegistrationType.php
  src/AppBundle/Form/UserType.php
Labels: Correction Done, Reviewed by PO

#35 S3 us05 formulair lycee creation
  app/Resources/views/department/edit.html.twig
  app/Resources/views/department/index.html.twig
  app/Resources/views/department/new.html.twig
  app/Resources/views/department/show.html.twig
  app/Resources/views/lycee/edit.html.twig
  app/Resources/views/lycee/index.html.twig
  app/Resources/views/lycee/new.html.twig
  app/Resources/views/lycee/show.html.twig
  package-lock.json
  src/AppBundle/Controller/DepartmentController.php
  src/AppBundle/Controller/LyceeController.php
  src/AppBundle/Entity/Department.php
  src/AppBundle/Entity/Lycee.php
  src/AppBundle/Form/DepartmentType.php
  src/AppBundle/Form/LyceeType.php
  src/AppBundle/Repository/DepartmentRepository.php
  src/AppBundle/Repository/LyceeRepository.php
  src/AppBundle/Tests/Controller/DepartmentControllerTest.php
  src/AppBundle/Tests/Controller/LyceeControllerTest.php
  webpack.config.js
Labels: Correction Done, Reviewed by PO

#44 correction IntegerType Lycee
  src/AppBundle/Form/LyceeType.php
Labels: Reviewed by PO

#45 Dev to Master
  app/Resources/views/department/edit.html.twig
  app/Resources/views/department/index.html.twig
  app/Resources/views/department/new.html.twig
  app/Resources/views/department/show.html.twig
  app/Resources/views/lycee/edit.html.twig
  app/Resources/views/lycee/index.html.twig
  app/Resources/views/lycee/new.html.twig
  app/Resources/views/lycee/show.html.twig
  package-lock.json
  src/AppBundle/Controller/DepartmentController.php
  src/AppBundle/Controller/LyceeController.php
  src/AppBundle/Entity/Department.php
  src/AppBundle/Entity/Lycee.php
  src/AppBundle/Form/DepartmentType.php
  src/AppBundle/Form/LyceeType.php
  src/AppBundle/Repository/DepartmentRepository.php
  src/AppBundle/Repository/LyceeRepository.php
  src/AppBundle/Tests/Controller/DepartmentControllerTest.php
  src/AppBundle/Tests/Controller/LyceeControllerTest.php
  webpack.config.js
Labels: Reviewed by PO

#58 Ajout des metiers dans la création fiche + liaison statut par defaut.
  app/Resources/views/base.html.twig
  app/Resources/views/sheet/index.html.twig
  app/Resources/views/sheet/new.html.twig
  app/Resources/views/sheet/show.html.twig
  assets/js/app.js
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/Entity/Sheet.php
  src/AppBundle/Form/SheetType.php
  src/AppBundle/Tests/Controller/SheetControllerTest.php
Labels: Reviewed by PO

#57 S4 us03 editon
  app/Resources/views/metier/edit.html.twig
  app/Resources/views/metier/new.html.twig
  assets/scss/form.scss
  src/AppBundle/Controller/MetierController.php
Labels: Reviewed by PO

#63 S4 us08-page de gestion
  app/Resources/views/admin/management.html.twig
  app/Resources/views/layout_admin.html.twig
  src/AppBundle/Controller/ManagementController.php
Labels: Reviewed by PO

#65 correction orthographe
  app/Resources/FOSUserBundle/views/Security/login.html.twig
  app/Resources/views/lycee/new.html.twig
  app/Resources/views/metier/new.html.twig
  app/Resources/views/sheet/new.html.twig
  app/config/security.yml
  src/AppBundle/DataFixtures/AppFixtures.php
  src/AppBundle/Form/LyceeType.php
  src/AppBundle/Form/MetierType.php
  src/AppBundle/Form/SheetType.php
  src/AppBundle/Form/UserType.php
Labels: Correction Done, Reviewed by PO

#66 dev to master
  app/Resources/FOSUserBundle/views/Security/login.html.twig
  app/Resources/views/admin/management.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/layout_admin.html.twig
  app/Resources/views/lycee/new.html.twig
  app/Resources/views/metier/edit.html.twig
  app/Resources/views/metier/new.html.twig
  app/Resources/views/sheet/index.html.twig
  app/Resources/views/sheet/new.html.twig
  app/Resources/views/sheet/show.html.twig
  app/config/security.yml
  assets/js/app.js
  assets/scss/form.scss
  assets/scss/main.scss
  src/AppBundle/Controller/ManagementController.php
  src/AppBundle/Controller/MetierController.php
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/DataFixtures/AppFixtures.php
  src/AppBundle/Entity/Sheet.php
  src/AppBundle/Form/LyceeType.php
  src/AppBundle/Form/MetierType.php
  src/AppBundle/Form/SheetType.php
  src/AppBundle/Form/UserType.php
  src/AppBundle/Tests/Controller/SheetControllerTest.php
Labels: Reviewed by PO

#67 S4 us04 suppression
  app/Resources/views/metier/edit.html.twig
  app/Resources/views/metier/new.html.twig
  assets/scss/form.scss
  src/AppBundle/Controller/MetierController.php
Labels: Reviewed by PO

#68 S4 us01 fk user sheet
  app/Resources/views/sheet/index.html.twig
  app/Resources/views/sheet/new.html.twig
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/Entity/Sheet.php
Labels: Correction Done

#71 S4 - Fix responsive page Login
  app/Resources/FOSUserBundle/views/Security/login.html.twig
  assets/scss/form.scss
Labels: Reviewed by PO

#73 correction sheet controleur, form scss
  assets/scss/form.scss
  src/AppBundle/Controller/SheetController.php
Labels: Reviewed by PO

#74 dev to master
  app/Resources/FOSUserBundle/views/Security/login.html.twig
  app/Resources/views/admin/history.html.twig
  app/Resources/views/metier/edit.html.twig
  app/Resources/views/metier/new.html.twig
  app/Resources/views/sheet/index.html.twig
  app/Resources/views/sheet/new.html.twig
  assets/scss/form.scss
  assets/scss/main.scss
  src/AppBundle/Controller/HistorySheetController.php
  src/AppBundle/Controller/MetierController.php
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/Entity/Sheet.php
Labels: Reviewed by PO

#87 S5 us03 sheet date
  app/Resources/views/admin/history.html.twig
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/Entity/Sheet.php
Labels: Reviewed by PO

#70 S4 us05 edit lycee
  app/Resources/views/department/edit.html.twig
  app/Resources/views/department/index.html.twig
  app/Resources/views/department/new.html.twig
  app/Resources/views/department/show.html.twig
  app/Resources/views/lycee/edit.html.twig
  app/Resources/views/lycee/show.html.twig
  src/AppBundle/Controller/DepartmentController.php
  src/AppBundle/Controller/LyceeController.php
  src/AppBundle/Entity/Lycee.php
  src/AppBundle/Form/DepartmentType.php
  src/AppBundle/Form/LyceeType.php
  src/AppBundle/Tests/Controller/DepartmentControllerTest.php
Labels: Correction Done

#89 S5 us2 analysis
  app/Resources/views/analysis/edit.html.twig
  app/Resources/views/analysis/index.html.twig
  app/Resources/views/analysis/new.html.twig
  app/Resources/views/analysis/show.html.twig
  assets/scss/main.scss
  src/AppBundle/Controller/AnalysisController.php
  src/AppBundle/DataFixtures/AnalysisFixtures.php
  src/AppBundle/DataFixtures/StatusFixtures.php
  src/AppBundle/Entity/Analysis.php
  src/AppBundle/Form/AnalysisType.php
  src/AppBundle/Repository/AnalysisRepository.php
  src/AppBundle/Tests/Controller/AnalysisControllerTest.php
Labels: Reviewed by PO

#91 ajout du theme bootswatch lux
  assets/scss/main.scss
Labels: Reviewed by PO

#88 S5_us01_description-login
  app/Resources/FOSUserBundle/views/Security/login.html.twig
  assets/scss/main.scss
  assets/scss/variables.scss
Labels: Reviewed by PO

#93 Appfixture rename to MetierFixture
  src/AppBundle/DataFixtures/MetierFixtures.php
Labels: Reviewed by PO

#90 layaout-unification boutton plus modification metier
  app/Resources/views/lycee/new.html.twig
  app/Resources/views/metier/edit.html.twig
  app/Resources/views/metier/new.html.twig
  app/Resources/views/sheet/new.html.twig
  app/Resources/views/statut/edit.html.twig
  app/Resources/views/user/new.html.twig
  assets/scss/form.scss
Labels: Reviewed by PO

#94 S5-Fix-Fixture-User -> Ajout fixture user + modification role dans usertype
  src/AppBundle/DataFixtures/UserFixtures.php
  src/AppBundle/Form/UserType.php
Labels: Reviewed by PO

#97 Fix fixture sheet
  src/AppBundle/DataFixtures/MetierFixtures.php
  src/AppBundle/DataFixtures/SheetFixtures.php
  src/AppBundle/DataFixtures/UserFixtures.php
Labels: Reviewed by PO

#109 S6 us06 #01 navbar
  app/Resources/views/layout_admin.html.twig
  app/Resources/views/layout_emop.html.twig
  app/Resources/views/layout_school.html.twig
  app/config/security.yml
  assets/scss/navbar.scss
  src/AppBundle/Controller/HistorySheetController.php
  src/AppBundle/Controller/SheetController.php
Labels: Correction Done

#111 S6 us01-profil-create
  app/Resources/FOSUserBundle/views/Profile/show.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#114 home page des lycée
  app/Resources/views/school/index.html.twig
  src/AppBundle/Controller/SheetController.php
Labels: Reviewed by PO

#113 S6_FIX_S06-FIX-LAYOUT-ADMIN + LINK SHEET
  app/Resources/views/emop/history_emop.html.twig
  app/Resources/views/emop/sheet_edit.html.twig
  app/Resources/views/sheet/edit.html.twig
  app/Resources/views/sheet/new.html.twig
  src/AppBundle/Controller/SheetController.php
Labels: Correction Done

#126 FIX_S6_US06_#01 Ajout lastName - firstName profil + FIX EDIT LABEL !
  app/Resources/FOSUserBundle/views/Profile/edit.html.twig
  app/Resources/FOSUserBundle/views/Profile/show.html.twig
Labels: Reviewed by PO

#131 Fix de la page login
  app/Resources/FOSUserBundle/views/Security/login.html.twig
  app/config/security.yml
  assets/scss/form.scss
  assets/scss/main.scss
  assets/scss/variables.scss
Labels: Reviewed by PO

#127 modification path et class de button
  app/Resources/views/lycee/new.html.twig
  app/Resources/views/metier/edit.html.twig
  app/Resources/views/metier/new.html.twig
  app/Resources/views/sheet/new.html.twig
Labels: Reviewed by PO

#129 FIX jquery message FLASH
  app/Resources/views/base.html.twig
  app/Resources/views/default/index.html.twig
  assets/js/app.js
  assets/scss/main.scss
  src/AppBundle/Controller/SheetController.php
Labels: Reviewed by PO

#133 FIX_SERVICE POUR REDIRECT SELON ROLE APRES LOGIN + REGLAGE BUG NAVBAR
  app/Resources/views/layout.html.twig
  app/Resources/views/layout_admin.html.twig
  app/config/security.yml
  app/config/services.yml
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/Service/AfterLoginRedirection.php
Labels: Reviewed by PO

#134 fix responsive accueil lycée
  app/Resources/views/school/index.html.twig
Labels: Reviewed by PO

#136 S 06 fix fixture
  app/Resources/FOSUserBundle/views/Profile/show.html.twig
  src/AppBundle/DataFixtures/MetierFixtures.php
  src/AppBundle/DataFixtures/SheetFixtures.php
  src/AppBundle/DataFixtures/UserFixtures.php
Labels: Reviewed by PO

#138 fix route et layout
  app/Resources/views/admin/history.html.twig
  app/Resources/views/analysis/new.html.twig
  app/Resources/views/emop/history_emop.html.twig
  app/Resources/views/layout_emop.html.twig
  app/Resources/views/layout_school.html.twig
  app/Resources/views/lycee/edit.html.twig
  app/Resources/views/lycee/new.html.twig
  app/Resources/views/sheet/show.html.twig
  app/Resources/views/statut/edit.html.twig
  app/Resources/views/statut/new.html.twig
  app/Resources/views/user/new.html.twig
  src/AppBundle/Controller/MetierController.php
Labels: Reviewed by PO

#139 Fix_sheet_show
  app/Resources/views/sheet/show.html.twig
Labels: Reviewed by PO

#140 Dev to Master Sprint #6
  app/Resources/FOSUserBundle/views/Profile/edit.html.twig
  app/Resources/FOSUserBundle/views/Profile/show.html.twig
  app/Resources/FOSUserBundle/views/Security/login.html.twig
  app/Resources/views/admin/history.html.twig
  app/Resources/views/analysis/new.html.twig
  app/Resources/views/base.html.twig
  app/Resources/views/default/index.html.twig
  app/Resources/views/emop/history_emop.html.twig
  app/Resources/views/emop/sheet_edit.html.twig
  app/Resources/views/layout.html.twig
  app/Resources/views/layout_admin.html.twig
  app/Resources/views/layout_emop.html.twig
  app/Resources/views/layout_school.html.twig
  app/Resources/views/lycee/edit.html.twig
  app/Resources/views/lycee/new.html.twig
  app/Resources/views/metier/edit.html.twig
  app/Resources/views/metier/new.html.twig
  app/Resources/views/school/index.html.twig
  app/Resources/views/sheet/edit.html.twig
  app/Resources/views/sheet/new.html.twig
  app/Resources/views/sheet/show.html.twig
  app/Resources/views/statut/edit.html.twig
  app/Resources/views/statut/new.html.twig
  app/Resources/views/user/new.html.twig
  app/config/config.yml
  app/config/security.yml
  app/config/services.yml
  assets/js/app.js
  assets/scss/form.scss
  assets/scss/main.scss
  assets/scss/navbar.scss
  assets/scss/variables.scss
  composer.lock
  package-lock.json
  src/AppBundle/Controller/HistorySheetController.php
  src/AppBundle/Controller/MetierController.php
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/DataFixtures/DepartmentFixtures.php
  src/AppBundle/DataFixtures/MetierFixtures.php
  src/AppBundle/DataFixtures/SheetFixtures.php
  src/AppBundle/DataFixtures/UserFixtures.php
  src/AppBundle/Entity/Analysis.php
  src/AppBundle/Entity/Sheet.php
  src/AppBundle/Form/ProfilType.php
  src/AppBundle/Service/AfterLoginRedirection.php
  var/SymfonyRequirements.php
Labels: Reviewed by PO

#137 S6 us02 sheet edit
  app/Resources/views/emop/sheet_edit.html.twig
  app/Resources/views/lycee/edit.html.twig
  app/Resources/views/school/index.html.twig
  app/Resources/views/sheet/index.html.twig
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/Entity/Sheet.php
  src/AppBundle/Form/SheetType.php
Labels: Reviewed by PO

#146 Fixlycee
  src/AppBundle/DataFixtures/DepartmentFixtures.php
  src/AppBundle/DataFixtures/LyceeFixtures.php
Labels: Reviewed by PO

#153 fix index lycee analysis
  app/Resources/views/school/index.html.twig
Labels: Reviewed by PO

#154 S6 us04 trier par departement v3.0
  app/Resources/views/admin/history.html.twig
  app/Resources/views/lycee/edit.html.twig
  app/Resources/views/lycee/index.html.twig
  app/Resources/views/lycee/new.html.twig
  app/Resources/views/lycee/show.html.twig
  app/Resources/views/user/edit.html.twig
  app/Resources/views/user/index.html.twig
  app/Resources/views/user/show.html.twig
  src/AppBundle/Controller/HistorySheetController.php
  src/AppBundle/Controller/LyceeController.php
  src/AppBundle/Controller/UserController.php
  src/AppBundle/Entity/Department.php
  src/AppBundle/Entity/Lycee.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/HistorySheetType.php
  src/AppBundle/Form/LyceeType.php
  src/AppBundle/Repository/SheetRepository.php
  src/AppBundle/Tests/Controller/LyceeControllerTest.php
Labels: Reviewed by PO

#152 S6_US07 user comments
  app/Resources/views/base.html.twig
  app/Resources/views/comment/edit.html.twig
  app/Resources/views/comment/index.html.twig
  app/Resources/views/comment/new.html.twig
  app/Resources/views/comment/show.html.twig
  app/Resources/views/sheet/show.html.twig
  assets/scss/main.scss
  assets/scss/variables.scss
  src/AppBundle/Controller/CommentController.php
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/DataFixtures/CommentFixtures.php
  src/AppBundle/DataFixtures/SheetFixtures.php
  src/AppBundle/Entity/Comment.php
  src/AppBundle/Entity/Sheet.php
  src/AppBundle/Entity/User.php
  src/AppBundle/Form/CommentType.php
  src/AppBundle/Repository/CommentRepository.php
  src/AppBundle/Tests/Controller/CommentControllerTest.php
Labels: Reviewed by PO

#158 S7 us02 create password user
  app/Resources/FOSUserBundle/views/Resetting/reset.html.twig
  app/Resources/views/email/password_resetting.html.twig
  app/Resources/views/user/new.html.twig
  app/config/config.yml
  app/config/config_dev.yml
  app/config/security.yml
  src/AppBundle/Controller/MaillerController.php
  src/AppBundle/Controller/UserController.php
  web/images/logo_mail.jpg
Labels: Correction Done, Reviewed by PO

#166 Fix_Dev_S7
  app/Resources/views/base.html.twig
  src/AppBundle/DataFixtures/CommentFixtures.php
  src/AppBundle/DataFixtures/LyceeFixtures.php
  src/AppBundle/DataFixtures/SheetFixtures.php
  src/AppBundle/DataFixtures/UserFixtures.php
  src/AppBundle/Entity/User.php
Labels: Reviewed by PO

#161 Fix_sheet_new_layout
  app/Resources/views/sheet/show.html.twig
Labels: Reviewed by PO

#163 S7_US06_Management_buttons
  app/Resources/views/admin/management.html.twig
  assets/scss/main.scss
Labels: Reviewed by PO

#164 Fix create custom error
  app/Resources/TwigBundle/views/Exception/error.html.twig
  app/Resources/TwigBundle/views/Exception/exception.html.twig
  app/Resources/TwigBundle/views/layout.html.twig
  app/Resources/views/default/index.html.twig
Labels: Reviewed by PO

#165 S7_US01_Sheet_edit_analysis
  app/Resources/views/emop/sheet_edit.html.twig
  app/Resources/views/sheet/show.html.twig
  src/AppBundle/Controller/SheetController.php
  src/AppBundle/Entity/Sheet.php
  src/AppBundle/Form/SheetType.php
Labels: Reviewed by PO

#170 Fix navbar
  app/Resources/views/layout.html.twig
  app/Resources/views/layout_admin.html.twig
  assets/scss/navbar.scss
Labels: Correction Done

#176 Bouton 'retour' après arrivée sur la page 404 et modif de routing.yml
  app/Resources/TwigBundle/views/Exception/error.html.twig
  app/Resources/TwigBundle/views/Exception/exception.html.twig
  app/config/routing.yml
Labels: Reviewed by PO

#177 fix dev pour master
  src/AppBundle/Controller/LyceeController.php
  src/AppBundle/Controller/MetierController.php
Labels: Reviewed by PO
